<h3>Find the right fit</h3>
<p>Quite often I talk with potential clients looking for a website re-design/re-development because their current web designer is hard to get a hold of, not returning emails, or has just left them hanging altogether. In all honestly I feel bad for these people and is what prompted me to write this article because no one likes to be ripped off nor likes to hear about people getting ripped off. I know the title says web "company" however these principles definitely apply to web "freelancers" as well.</p>

<p>There are quite a few principles I recommend following as well as red flags to look for when starting the process of selecting the right company and/or individual to design your website. Remember, the bottom line is you need to find a company who is the right fit for you. Look at it as similar to car shopping. You want to focus on reliability, craftsmanship/design, efficiency, reputation, safety rating, warranty and affordability. The same applies when you choose a web design company.</p>
<ul>  
	<li><p><strong>Define your needs</strong>. Before you begin your search, you need to have a solid idea of what your needs are. Will your site be informational only or will you be selling products? Will you be doing the updates or do you want to pay for someone to do it for you?  Look at other websites that have the functionality and look you are striving for. You should also have a ballpark budget on what you can spend. Having a solid plan with this information will help determine what types of services you'll need.</p></li>

	<li><p><strong>Review their work</strong>. Most web companies have their portfolios and services listed on their website. See if your needs fall into their service offerings and review their current work. You'll definitely want to look for companies with a diverse portfolio.</p></li> 

	<li><p><strong>Contact references</strong>.  The best way to find out how reputable a web design company is to contact current and past customers who have had work done. I'm not a huge fan of online reviews or testimonials because quite honestly you have no idea if they are legit and who wrote them. On the other hand contacting and talking with someone who has worked with the company before will be give you the best insight as to their quality of work and overall customer experience.</p></li>

	<li><p><strong>Meet face-to-face</strong>. A lot of people I talk to who have been ripped off say they never met their web designer(s) face-to-face. What??!! If working with a local company is critical in your decision, always setup a meeting, preferably at their office so you can see if first, it's a legitimate business and second, to actually meet the people who will be doing the work. Ask as many questions as possible with the attitude that there's no such thing as a dumb question. Things to look for on an agency's website is local phone number and physical address (not a P.O. Box) as well as a staff page. If all you see is a 1-800 number it's a red flag that they aren't local. It's also common for a small 2-person shop or even a single person to design a site that makes them look bigger than they really are. </p></li>

	<li><p><strong>Read the fine print</strong>. When meeting face-to-face ask to see the contract and definitely read the fine print. Reviewing the design workflow and timeline is important, but so are the contractual obligations by you and the company. Key things to pay close attention to are all the fees (hosting, maintenance, etc.) and refund policies. You want to make sure if they default in any way you are not charged extra money.</p></li>

	<li><p><strong>Go with a reputible/recognizable company</strong>. If localization isn't a factor, but budget is, my recommendation would be to go with one of the big companies such Squarespace, WIX or GoDaddy. At least you know you're dealing with an recognizable company with customer service, large user community, etc.</p>

<p><a href="articles" title="Back to Articles">&lsaquo;&lsaquo; Back to Articles</a></p>