<h3>Where it all started</h3>

<p>In regards to the website...wow, I designed and built the first version (Bamboo Digital dot com back then) in 1999. Back then I was into web design and still doing some graphic design as a hobby so it was a fun platform to showcase my work. 
<p>I was born in Hawaii (Honolulu) and grew up in Seattle. My entire family still reside over there and I will always call it my home away from home. The laid back "island style" runs through my veins and is what has kept me level headed and relaxed in life thus far. The people and atmosphere in Hawaii are definitely one of a kind in the world.<p> I received my <strong>Bachelor of Fine Arts (BFA) </strong>in<strong> Graphics/Media Design</strong> from <strong>Washington State University</strong> (GO COUGS!). I was the only one that year who applied for the BFA program with a graphic design emphasis and got accepted on my first try. Upon graduating I had the opportunity to do a 6-month internship on campus at the Information Technology graphics lab with the hopes of landing a job back home in Seattle.</p>

<p>When I returned home to Seattle I hooked up with a staffing agency while applying for graphic design jobs and after working a handful of office jobs I was offered a 10 day contract at Boeing as an office admin. To make a long story short that 10 day contract turned into 10 months and eventually my foot in the door as a full time employee and a 15-year journey.  What I learned during my first year is how diverse Boeing's operations are and that there's a lot more to the company than just building airplanes. This was the first major shift in my career focusing on business, Information Systems and Technology. It was also during this period where I was introduced to web design and coding which would have a huge impact in my career. Having had little to no business experience from college I applied and got accepted in the graduate program at City University and received my <strong>MBA </strong>in <strong>Management Information Systems</strong>. </p>

<p>I currently work at <a href="http://www.seattlewebdesign.com" title="Seattle Web Design" target="_blank">efelle creative</a> a web design firm in downtown Seattle. The owner is a childhood friend of mine and as they say, it was destined that one day we'd work together. I've been with the company over 10 years now and have held multiple positions including Front-end Developer, Business Development and everything in between. In late 2019 I moved out of the Account Management world and into a more specialized role working with our eCommerce clients in customization/integration needs. I Love our diverse portfolio of clients and am blessed to be part of such a great company and <a href="http://www.seattlewebdesign.com/staff" title="team efelle" target="_blank">team</a>. </p>

<p>Outside of work my hobbies include training at the gym and playing golf both of which I relate to my career and work ethic. Both require focus, dedication, patience and concentration. The best part is you're constantly challenging and pushing yourself. The main thing is I'm having fun and able catch up with friends. I've learned to incorporate these criteria into my career path and so far have had a fun journey "on and off the course". My other hobbies include cooking, craft beers, reading up on sports nutrition and training, watching movies, looking for deals online, hanging out with friends, going to Hawaii to spend time with my family and sometimes...just being a homebody and relaxing!</p>

<p>Lastly I wanted to talk about a piece of advice I received during a memorable round golf. A while back my friend and I got paired with an older woman from Australia who happened to be out of all things, a sports psychologist. As the round went on the conversation shifted on how golf was a mentally frustrating game. She told us most amatuer golfers have one critical flaw in common; we concentrate on the end result rather than the next shot. When you do this you lose focus on the current task at hand. I thought about this for a minute and realized she was right! I've come to learn and use this same technique in my everyday life and career. Having patience and doing things one step at a time has been a big factor in my achievements. For the round of golf that day, I ended up shooting a 77, my best round to date!</p>