<h3>Answers to common questions</h3>

<p><strong>What do you enjoy about account management and what are the challenges?</strong></p>
<p>The best thing about my job is the client interaction. I've always been a people person and enjoy meeting learning more about them. The unique role and responsibility of account management is not only managing projects and taking care of clients, but forming long-term relationships. I particularly enjoy the ability to help and mentor them in a support role, rest assured they can always contact me for any questions/concerns. It's important to me to create friendships as well as business relationships. I can only speak for my current company, but we want to make all our clients feel like part of our family, not just another client.</p>

<p>The main challenge I've faced in my career is the different personalities you encounter. Whether it be in customer service, consulting role (sales) or account management you'll be interacting and forming relationships with people with diverse personalities from all demographics. In our agency, every project is unique along with the clients and their team. Strong people and interpersonal skills is key! Client personalities can range from extremely easy going and open minded to the complete opposite and everything in between. I use the phrase "hope for the best (be positive), expect anything" because whatever happens you have to maintain a positive attitude throughout the process. If you go into a project having doubts or with a negative attitude you're setting a weak foundation which will be susceptible to problems along the journey.</p>  

<p><strong>How did you get started in Web Design/Development?</strong></p>
<p>My background out of college was graphic design. I had just been hired at Boeing and was working in the desktop support group when my co-worker and friend Christian Booth suggested I try designing and building a website. Build a website?? I had no idea what he was talking about so he quickly opened Notepad and typed in "hello world" and then added in some simple HTML to change the font color. That was my "holy crap" moment and was hooked right then and there. I bought a HTML book and never looked back. It's a pretty generic story, but crazy how you stumble across things in life that end up becoming one of your life long passions. Even though I'm embarking on a new journey in my career away from coding full time, I'll always have one hand in it. I still help with front-end development support at work and also manage some websites for friends and family. </p>

<p><strong>Advice for folks starting their career journey:</strong></p>

<p>My thinking is pretty simple; don’t lose focus on your happiness and quality of life and always keep your eyes open to opportunities. You want your career to be a fun journey and not a 30 year grind. If you ever start dreading going to work, it probably means you need a change. This can be a change in roles or even change in scenary and work environment. I’ve worked with a lot of folks who were miserable and whose only focus was on the next paycheck and their retirement. It was interesting learning why they never ventured to another company or career path and the common thing I heard was that’s the way they were taught. Their generation and the previous ones worked at a single company and retired at the same one so this is how they grew up thinking. I was on the tail end of this generation and after the 5 year mark at my first company got sucked into this mentality thinking I was going to retire there. The term back then was “lifer”. It’s funny how 5 years becomes 10, then 15, but I get it. You’re making a great salary, benefits are off the charts (my grad school was paid in full), 401k matching is awesome, you get comfortable. On the flip side though, how happy are you? It’s when I started at my new company that I had time to dwell on the previous 15 years and realized I wasn’t completely happy the entire time, and as I mentioned before, got in the “comfort” zone. If I could go back and do things differently I would've ventured out and experienced opportunities at other companies like the one I’m at now. My message is to take a break from time to time and evaluate how happy you are with your job and field you’re in. You can also take it one step further and make a mental journal of your likes and dislike of your job. As I'm writing this more people than ever nation-wide are enduring emmence pressure and stress from their jobs. I don't know one friend off hand that isn't experiencing some form of stress or anxiety including myself. Even though most of us embrace it the health issues shouldn't be overlooked. This is why its more important than ever to take charge of your happiness. At the end of the day, it's all about quality of life!</p>

<p><strong>Advice for folks starting out in Web Development</strong></p>

<p>I know the learning approach has changed since I first started. There is a wide assortment of development bootcamps for rapid learning, however I'm still a believer in getting a good handle on the bare bones fundamentals and then building your skills from there. I see folks jumping straight into Javascript or PHP tutorials with no understanding of basic HTML or how to build a basic web page and then wonder why they are so overwhelmed and confused. Ok, you built this JS calculator, can you now implement it into a website? I usually get a blank stare (lol). My recommendation is to learn basic HTML and CSS and build a bare bones website and then start manipulating the layout and aesthetics. Again, learn and get a good understanding of the foundation and fundamentals. Diving in head first to PHP or other languages will only cause you frustration and confusion. At least that was my experience early on.</p>

<p><strong>What are your hobbies outside of work?</strong></p>

<p>I’d say my number one hobby outside of work is training at the gym. It's an addiction and has been a part of my lifestyle for over 20 years so I’m not sure if that counts as a hobby or not, but I love it. When it comes down to it I'm a gym rat for life! I’ve been into athletics since I was a kid and weight training was something I got hooked on as soon as I lifted my first weight in high school. I follow the sport of bodybuilding year round and enjoy reading up on new training techniques and nutrition. I recently took up cycling so am on my bike the days I'm not in the gym. </p> 

<p>Golf is another passion of mine I took up during college. Unfortunately where we live it’s something I don’t play year round however my yearly trip to Hawaii to visit my family allows me to get a few rounds in during the winter months. There is so much mental aspects of golf it can drive you crazy at times, but it’s a sport where you’re constantly thinking which is the fun part. As I’ve gotten older the game has become more fun (less cussing, throwing clubs) and play for the fun of it. I get to drink a few beers, have some laughs and catch up with my buddies.</p>

<p>Food and craft beers are some other things I really enjoy. I’ve really only gotten into craft beers the past few years and have taken the time to really learn about the different varieties. We’re spoiled with good beer up here in the Northwest (Washington/Oregon) along with the food scene thriving every year. There’s nothing better than a cold IPA from a brewery right in your backyard! So what's my favorite brewery? Well, there are too many to name, but as of right now I'd have to say Breakside Brewery in Oregon hands down! Sorry Washington.</p>

<p><strong>Advice for folks starting out on an exercise regiment:</strong></p>

<p>First off I’m always excited to hear friends and family members, friends of friends or whomever who decide to take an active approach in bettering their health. As much as I enjoy eating good food and drinking delicious craft beers, I’m also a bonafide gym junkie and health and fitness advocate. There are hundreds of approaches I've read about in various forums and magazines, however when someone asks me how to start on an exercise regiments, I tell them to keep it simple. It’s not rocket science when it comes to diet and exercise however you need a plan and ‘ease’ into those changes. Everyone's body is different so it's important to create a training/diet regiment that works for you and to adjust it as you get older and your body changes. That's the fun part of the journey. Try new exercises and food and take note of what works and what doesn't. It's all about trial and error and dialing everything in like a well oiled machine.   

The one word I use a lot is ‘moderation’ because a lot of folks I talk to don’t have that word in their vocabulary or have no idea what that means. Cheat foods, etc. are ok, but you should sprinkle those things in "moderation". If you eat fast food 5 days a week, try cutting that down to 4 times, then 3 times, etc. The same goes for exercise (e.g. - gym, walk, bike), start off slow doing 30 mins a day a few days a week, then keep increasing it along with intensity. The mistake I see all the time is people doing just the opposite of this. My fitness and bodybuilding peeps know exactly what I’m talking about. It’s usually January (famous New Year's resolution, hehe), they go on a hardcore crash diet and work out balls to the wall 7 days a week right out of the gate. What happens? Well it’s called burnout. I’ll see these folks in the gym for a couple weeks, see all the posts on Facebook on how they’re “killing it” in the gym, ran 10 miles on the treadmill, down 10 pounds and then all a sudden disappear. I’ll run into them only to hear how they were sore for 2 weeks, miserable and couldn’t stand the change in diet and gave up. It’s all because integrating healthy habits to your daily regiment is a lifestyle change that you need to ease into it with baby steps.  Choose forms of exercise that are fun and enjoyable. Slowly integrate more healthy foods into your diet while minimizing the bad stuff, while…still allowing for cheat meals or snacks. And lastly who ever said you have to join a gym to get excercise???? Find something fun you enjoy doing where you're actually "moving" and stick to those things or join Planet Fitness...I'm joking. Haha. Don't join Planet Fitness. </p>